---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/init
    tag: latest

inputs:
- name: bosh-utils
  path: gopath/src/github.com/EngineerBetter/bosh-utils
- name: version-semver

outputs:
- name: compiled-darwin

params:
  GOOS:   darwin
  GOARCH: amd64

run:
  path: gopath/src/github.com/EngineerBetter/bosh-utils/ci/tasks/build-multidigest-binary.sh
