---
platform: windows

inputs:
- name: bosh-utils
  path: gopath/src/github.com/EngineerBetter/bosh-utils

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - gopath/src/github.com/EngineerBetter/bosh-utils/ci/tasks/test-unit.ps1
