---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/init

inputs:
- name: bosh-utils
  path: gopath/src/github.com/EngineerBetter/bosh-utils

run:
  path: gopath/src/github.com/EngineerBetter/bosh-utils/ci/tasks/test-unit.sh
